image: ruby:2.5
cache:
  paths:
    - .bundle
variables:
  JEKYLL_ENV: production

before_script:
  - bundle --path .bundle/gems
pages:
  script:
    - bundle exec jekyll build -d public --config _config.yml,_config-gitlab.yml -q
  artifacts:
    paths:
      - public
  only:
    - master