image: asciidoctor/docker-asciidoctor:1.35
cache:
  paths:
    - .bundle
before_script:
  - gem install bundler
  - bundle --path .bundle/gems
pages:
  script:
    - bundle exec jekyll build -d public --config _config.yml,_config-gitlab.yml -q
  artifacts:
    paths:
      - public
  only:
    - master