image: ruby:3.1.3-alpine
cache:
  paths:
    - .bundle
variables:
  JEKYLL_ENV: production

before_script:
  - apk add --upgrade build-base ruby ruby-dev ruby-bundler openjdk11 graphviz ttf-dejavu
  - bundle --path .bundle/gems

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always



pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public --config _config.yml,_config-gitlab.yml -q
  artifacts:
    paths:
      - public
  only:
    - master