title: Sciam Tech Blog
description: Ce blog contient des articles techniques issus de la communeauté des salariés de SCIAM
baseurl: "/"
highlighter: rouge
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .idea
  - .jekyll-cache
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  excerpt_separator: "\n//more\n"
  attributes:
    - idseparator=_
    - source-highlighter=rouge
    - rouge-css=style
    - rouge-style=github
    - icons=font
