title: Blog Tech Sciam
description: Ce blog contient des articles techniques issus de la communeauté des salariés de SCIAM
url: "http://localhost:4000"
locale: fr_FR
baseurl: "/"
twitter:
  username: SCIAM_FR
  card: summary
highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      toc: true
      
social-network-links:
  github: 'SCIAM-FR'
  twitter: 'SCIAMVOX'
  medium: 'sciam-fr'
  linkedin: 'sciamfr'
  www: 'sciam.fr'
  gitlab: 'sciam'

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .idea
  - .jekyll-cache

keep_files:
  - images

asciidoc: {}

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  excerpt_separator: "\n//more\n"
  attributes:
    stem: latexmath
    idseparator: _
    source-highlighter: rouge
    source-language: java
    rouge-css: style
    rouge-style: github
    asciidoctor-stylesheet: asciidoctor.css
    icons: font
    imagesdir: "/images"

plugins:
  - jekyll-paginate-v2
  - jekyll-auto-authors
  - jekyll-asciidoc
  - asciidoctor-diagram
  - liquid_reading_time
  - liquid_pluralize
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

pagination:
  enabled: true
  per_page: 9
  paginate_path: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true

  # Other autopage configs stay the same

  tags:
    layouts:
      - "autopage_tags.html"
    title: "Articles taggué avec #:tag"
    permalink: "/tag/:tag"
    silent: false
    slugify:
      mode: "default"
      case: true

  authors:
    enabled: true
    data: '_data/authors.yml' # Data file with the author details
    layouts: 
      - 'autopage_author.html' # We'll define this layout later
    title: 'Articles par :author'
    permalink: '/author/:author/'
    slugify:
      mode: 'default' # choose from [raw, default, pretty, ascii or latin]
      cased: true # if true, the uppercase letters in slug will be converted to lowercase ones.

  categories:
    enabled: false

  collections:
    enabled: false

feed:
  excerpt_only: true

toc:
  min_level: 2
  max_level: 4
