title: Sciam Tech Blog
description: Ce blog contient des articles techniques issus de la communeauté des salariés de SCIAM
baseurl: "/"
highlighter: rouge

social-network-links:
  github: 'SCIAM-FR'
  twitter: 'SCIAM_FR'
  medium: 'sciam-fr'
  linkedin: 'sciamfr'
  www: 'sciam.fr'
  gitlab: 'sciam'

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .idea
  - .jekyll-cache

asciidoc: {}

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  excerpt_separator: "\n//more\n"
  attributes:
    - idseparator=_
    - source-highlighter=rouge
    - rouge-css=style
    - rouge-style=github
#    - asciidoctor-stylesheet=asciidoctor.css
    - icons=font

plugins:
  - jekyll-paginate-v2
  - jekyll-auto-authors

pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true

  # Other autopage configs stay the same

  tags:
    layouts:
      - "autopage_tags.html"
    title: "Articles taggué avec #:tag"
    permalink: "/tag/:tag"
    silent: false
    slugify:
      mode: "default"
      case: true

  authors:
    enabled: true
    data: '_data/authors.yml' # Data file with the author details
    layouts: 
      - 'autopage_author.html' # We'll define this layout later
    title: 'Article par :author'
    permalink: '/author/:author/'
    slugify:
      mode: 'default' # choose from [raw, default, pretty, ascii or latin]
      cased: true # if true, the uppercase letters in slug will be converted to lowercase ones.

  categories:
    enabled: false

  collections:
    enabled: false
