= Créez votre environnement de développement Quarkus en 10 minutes avec WSL
:author: pcheucle
:layout: post
:page-excerpt: Un guide pas à pas pour configurer un environnement de développement Quarkus prêt à l'emploi avec WSL.
:page-navtitle: Environnement Quarkus avec WSL
:page-tags: [WSL ,Windows Subsystem for Linux ,Ubuntu ,Java ,Quarkus, Visual Studio Code]
:post-vignette: wsl.png
:page-vignette: wsl.png
:page-vignette-licence: Sources: WSL, Quarkus
:showtitle:
:page-liquid:
:page-categories: software

Développer avec Quarkus sous Linux offre certains avantages comme le fait de bénéficier d’un système de fichiers sensible à la casse par défaut, de pouvoir installer plus facilement les prérequis à la compilation native ou encore de pouvoir compiler un exécutable natif de façon statique. 

Certains développeurs apprécieront également le fait de pouvoir développer dans un environnement proche voir identique à l’environnement d’exécution qui, dans la plupart des cas, est un conteneur Linux. 

Les développeurs travaillant sous Windows peuvent également bénéficier d’un environnement Linux sur leur machine, et cela n’a jamais été aussi simple depuis l’arrivée de Windows Subsystem for Linux (WSL).

Dans ce guide, nous allons voir comment configurer un environnement de développement Quarkus prêt à l'emploi avec WSL.


== L'installation d'Ubuntu dans WSL

La première étape de notre guide consiste à installer une distribution Linux dans WSL.

Dans un terminal Windows, nous exécutons la commande suivante : 

[source,shell]
----
wsl --install
----

La distribution Linux installée par défaut est Ubuntu, mais il est possible de spécifier une autre distribution Linux.

À la fin de l'installation, après avoir entré un nom d'utilisateur ainsi qu'un mot de passe, nous sommes redirigés vers le shell Bash d'Ubuntu.

Nous terminons cette étape par la mise à jour du système Ubuntu :
[source,shell]
----
sudo apt update && sudo apt -y upgrade
----

== L'installation de SDKMan!

SDKMan! est un outil facilitant l'installation et la gestion de SDKs (Java, Scala, Maven, Quarkus, etc.) sur les environnements de type Unix.

Nous devons au préalable installer les dépendances requises par SDKMan! :

[source,shell]
----
sudo apt-get install zip unzip
----

Puis nous installons SDKMan! :

[source,shell]
----
curl -s "https://get.sdkman.io" | bash
----

Enfin, nous exécutons la commande suivante pour rendre SDKMan! utilisable dans notre terminal :

[source,shell]
----
source "/home/user/.sdkman/bin/sdkman-init.sh"
----

== L'installation du JDK avec SDKMan!

SDKMan! permet d'installer différentes distributions du JDK.

Ici, nous installons Mandrel, une distribution dérivée de GraalVM Community Edition.
Cette distribution se comporte comme un JDK classique, mais permet également de compiler nativement des applications Quarkus, comme nous le verrons plus loin dans ce guide.

Pour installer Mandrel avec SDKMan!, nous exécutons la commande suivante :

[source,shell]
----
sdk install java 23.1.4.r21-mandrel
----

== L'installation de Quarkus CLI avec SDKMan!

Quarkus CLI est un outil permettant de créer des projets Quarkus, de gérer les extensions et de faciliter les tâches de développement et de build.

Pour installer Quarkus CLI avec SDKMan!, nous exécutons la commande suivante:

[source,shell]
----
sdk install quarkus
----

== La création d'un projet Quarkus avec Quarkus CLI

Nous allons maintenant créer un projet Quarkus de démonstration, qui nous sera utile pour les étapes suivantes de ce guide.

Nous créons au préalable un répertoire pour nos projets :

[source,shell]
----
mkdir projects
----

Puis, dans ce répertoire, nous créons notre projet Quarkus :

[source,shell]
----
cd projects
quarkus create app
----

Enfin, nous naviguons dans le répertoire du projet :

[source,shell]
----
cd code-with-quarkus
----

== La build d'un projet Quarkus avec Quarkus CLI

Pour lancer la build du projet, nous exécutons la commande suivante :

[source,shell]
----
quarkus build
----
Une fois la phase de build terminée, nous obtenons un fichier Jar exécutable.

Nous pouvons alors démarrer l'application :

[source,shell]
----
java -jar target/quarkus-app/quarkus-run.jar
----

Puis, nous vérifions le bon fonctionnement de l'application en allant sur http://localhost:8080/hello.

La page doit afficher le message suivant : Hello from Quarkus REST.

Nous pouvons maintenant quitter l'application (CTRL+C).


== La build native d'un projet Quarkus avec Quarkus CLI

Un des principaux avantages de Quarkus est de pouvoir compiler nativement une application afin que celle-ci démarre plus rapidement et soit moins consommatrice en ressources CPU et RAM.

Afin de pouvoir compiler nativement l'application, nous devons au préalable installer quelques dépendances :
[source,shell]
----
sudo apt-get -y install build-essential libz-dev zlib1g-dev
----

Nous pouvons alors exécuter la build native du projet avec Quarkus CLI :

[source,shell]
----
quarkus build --native
----

Une fois la build terminée, nous pouvons démarrer l'application avec la commande suivante :

[source,shell]
----
./target/code-with-quarkus-1.0.0-SNAPSHOT-runner
----

On notera que le démarrage de l'application est plus rapide que dans le cas d'un compilation classique.

== La build d'une image container avec Quarkus CLI

Il est très frequent d'avoir à construire une image container en vue de la déployer dans une infrastructure type Kubernetes.

Afin de pouvoir générer une image container, nous avons besoin d'un environnement d'exécution tel que Podman.

Nous installons Podman avec la commande suivante :

[source,shell]
----
sudo apt-get -y install podman
----

Nous ajoutons l'extension container-image-podman à notre projet Quarkus.
Cette dernière permet la génération d'images container via Podman.

[source,shell]
----
quarkus extension add container-image-podman
----

Nous pouvons alors exécuter la build de l'image container :

[source,shell]
----
quarkus image build podman --native -Dquarkus.native.container-build=true
----

Une fois la phase de build terminée, nous pouvons démarrer l'image container dans Podman :

[source,shell]
----
podman run localhost/user/code-with-quarkus:1.0.0-SNAPSHOT
----

== L'installation de Visual Studio Code pour développer en remote depuis WSL

Nous terminons ce guide par l'installation d'un éditeur de code qui nous permettra d'effectuer des changements dans notre projet Quarkus.

Visual Studio Code (VS Code), avec son extension WSL, permet d'éditer du code dans un environnement Linux depuis Windows, en mode *client-serveur*.

VS Code est disponible depuis https://code.visualstudio.com/.

Lors de l'installation, il est important de cocher l'option *Add to PATH*. Le PATH étant partagé entre Windows et Ubuntu, nous pourrons alors lancer VS Code directement depuis notre Shell Bash Ubuntu.

Une fois VS Code démarré, nous installons l'extension WSL depuis la vue *Extensions*.

Enfin, nous fermons puis relançons notre terminal Windows afin que la modification du PATH soit prise en compte, et que VS Code soit accessible depuis WSL. 

Une fois le terminal Windows rouvert, nous accédons au Shell Bash d'Ubuntu en exécutant la commande suivante :

[source,shell]
----
wsl
----

Puis nous ouvrons notre projet Quarkus dans Visual Studio Code :

[source,shell]
----
code /home/user/projects/code-with-quarkus/
----

VS Code démarre alors dans Windows puis installe la partie serveur sur notre environnement Ubuntu.
Une fois la partie serveur installée, le projet Quarkus s'ouvre dans l'éditeur.

== Conclusion

Nous avons vu dans ce guide à quel point il était simple et rapide de configurer un environnement Quarkus prêt à l'emploi avec WSL.
Les outils nécessaires pour pouvoir développer avec Quarkus sont installés de manière transparente, sans impacter la machine Windows.
Et grâce au mode remote de Visual Studio Code, il est également possible de développer dans WSL depuis Windows.
