= Article de test en AsciiDoc
:showtitle:
:page-navtitle: Article de test en AsciiDoc 
:page-excerpt: Article de test en AsciiDoc sur le blog
:layout: post
:page-auteurs: [antoinesabotdurand,jeanmicheldoudoux]
:page-tags: [Test,Java,Blog]
:page-toc: false
:page-vignette: 1_wP4DCPy7MxRbZGkCQ1y7tw.jpeg


== Paragraphes

Erat voluptua duo ipsum voluptua kasd placerat commodo imperdiet aliquam minim stet ut ipsum. Velit consetetur et et dolores illum nonumy nonumy ipsum ipsum luptatum diam. Ea lorem sed et sadipscing sed soluta sit sea laoreet vero est clita labore est et assum eu duis. Takimata erat consetetur iriure sadipscing elitr voluptua qui zzril dolor at magna sanctus ut labore et vulputate vel diam. Iriure no consectetuer lorem kasd.

Dolor vero aliquyam eu accusam et amet clita invidunt. Lorem diam amet lorem et ut gubergren no erat lorem nonumy sit erat quod sanctus aliquip ex magna dolor. Laoreet dolore diam diam erat doming velit consectetuer sanctus tempor sanctus. Ipsum amet tempor sadipscing imperdiet ad clita exerci odio sit te. Amet sit amet tempor nonummy.

 ligne 3

ligne1 en **gras** et en *italique* avec du texte ***important*** a mettre en evidence  

ligne2
ligne3 +
ligne4

== Formattage du texte

texte en _italique_, texte en *gras*.

+mono *bold*+, `mono pass thru`

normal, ^exposant^, ~indice~.

Dans un terminal DOS, tapez la commande `dir`.

== Listes

.Liste à puce
* puce 1
* puce 2
  - puce 2.1
  - puce 2.2
* puce 3
** puce 3.1
** puce 3.2
*** puce 3.2.1
*** puce 3.2.2
**** puce 3.2.2.1
**** puce 3.2.2.2
***** puce 3.2.2.2.1
***** puce 3.2.2.2.2
**** puce 3.2.2.3
*** puce 3.2.3
** puce 3.3
* puce 4

''''

== Mises en garde (Admonitions)

TIP: une astuce.

IMPORTANT: un point important.

WARNING: un avertissement.

CAUTION: attention.

.Titre de la note
NOTE: Exemple de notes
      Description de la note.


== Code source

[source,java]
----
public void doSomethingWithContextualMyClass() {
        BeanManager bm = CDI.current().getBeanManager();
        CreationalContext<MyClass> cctx = bm.createCreationalContext(null);
        MyClass myInstance = new MyClass(); //<1>
        it.postConstruct(myInstance); //<2>
        cctx.release();
}
----
<1> instance is not created by the container
<2> register the instance


[source,json]
----
{
  "firstName": "John",
  "lastName": "Smith",
  "age": 25
}
----

== Tableaux

.An example table
[options="header,footer"]
|=======================
|Col 1|Col 2      |Col 3
|1    |Item 1     |a
|2    |Item 2     |b
|3    |Item 3     |c
|6    |Three items|d
|=======================

== Caractères spéciaux

(C) (R) (TM) -- ... -> <- => <= &#182;

Copyright (©) — &copy;
Registered trademark (®) — &reg;
Trademark (™) — &trade;
Euro (€) — &euro;
Left arrow (←) — &larr;
Up arrow (↑) — &uarr;
Right arrow (→) — &rarr;
Down arrow (↓) — &darr;
Degree (°) — &#176;
Pi (π) — &#960;

== Schémas

PlantUML 

[plantuml, target=Article_de_test_diagram-classes, format=png]   
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

Ditaa

[ditaa,Article_de_test_memory,png]
....

      +--------+
   0  |        |  <- start
      +--------+
   1  |        |  <- q  scans from start to end
      +--------+
      :  ..... |
      +--------+
      |        |  <- end
      +--------+  <-+
      |        |    |
      +--------+    | rest of the
      :  ..... |    | allocated memory
      +--------+    |
  n   |        |    |
      +--------+  <-+
....

Graphviz

[graphviz,Article_de_test_cyclic,svg]
....
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
....